version: '3.9'

services:
  # reverse proxy with nginx
  web:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./build/nginx/templates/default-80-fastapi.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_HOST=${DOMAIN}
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
    expose:
      - 80
    networks:
      - default
      - proxy_default

  # frontend Streamlit
  streamlit:
    container_name: ${COMPOSE_PROJECT_NAME}-streamlit
    build:
      context: ./build/streamlit
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - '8501:8501'
    depends_on:
      - app
    networks:
      - default
      - proxy_default

  # backend FastAPI 
  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    build:
      context: ./build/app
      dockerfile: Dockerfile 
    volumes:
      - ./src:/app
    ports:
      - '8080:8080'
    environment:
      - NGINX_HOST=${DOMAIN}
    depends_on:
      - db
    networks:
      - default
      - proxy_default

  # database server width mariadb
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: mariadb:${MARIADB_TAG}
    # build:
    #   context: ./build/db
    #   dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./build/db/my.cnf:/etc/mysql/my.cnf
      - ./build/db/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./build/db/actress.sql:/docker-entrypoint-initdb.d/user.sql
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    networks:
      - default
      - proxy_default

networks:
  default:
  proxy_default:
    external: true
